apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bitcoin-comment-process-db-post-
spec:
  entrypoint: bitcoin-process-block
  templates:


  - name: bitcoin-comment-process-insert
    inputs:
      parameters:
      - name: url
    container:
      env:
      - name: POSTGRES_DATABASE
        valueFrom:
          secretKeyRef:
            name: postgres-secret-config
            key: dbname
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret-config
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret-config
            key: password
      - name: POSTGRES_HOST
        valueFrom:
          secretKeyRef:
            name: postgres-secret-config
            key: host
      - name: POSTGRES_PORT
        valueFrom:
          secretKeyRef:
            name: postgres-secret-config
            key: port
      image: gcr.io/kdcc-282418/bitcoin-worker
      command: [python]
      args: ["wfunc/wfunc/bitcoin-comment-process-db.py","{{inputs.parameters.url}}"]

  

  - name: bitcoin-process-block
    parallelism: 3
    steps:
    - - name: genrate-list-raw-comments
        template: genrate-list-raw-comments

    - - name: process-insert
        template: bitcoin-comment-process-insert
        arguments:
          parameters:
          - name: url
            value: "{{item}}"
        withParam: "{{steps.genrate-list-raw-comments.outputs.result}}"



  - name: genrate-list-raw-comments
    script:
      image: gcr.io/kdcc-282418/python-worker
      command: [python]
      source: |
        import json
        import sys
        from google.cloud import storage

        def get_file_names():
          files = []
          client = storage.Client()
          for blob in client.list_blobs('workflowkddc', prefix='Bitcoin/comments/raw/'):
            files.append(str(blob.name))
          return files
        
        json.dump(get_file_names(), sys.stdout)





  # - name: post-bitcoin
  #   script:
  #     image: gcr.io/kdcc-282418/python-worker
  #     env:
  #       - name: AWS_SECRET_ACCESS_KEY
  #         valueFrom:
  #           secretKeyRef:
  #             name: aws-secret-config
  #             key: access_key
  #       - name: AWS_ACCESS_KEY_ID
  #         valueFrom:
  #           secretKeyRef:
  #             name: aws-secret-config
  #             key: key_id
  #       - name: POSTGRES_DATABASE
  #         valueFrom:
  #           secretKeyRef:
  #             name: postgres-secret-config
  #             key: dbname
  #       - name: POSTGRES_USER
  #         valueFrom:
  #           secretKeyRef:
  #             name: postgres-secret-config
  #             key: username
  #       - name: POSTGRES_PASSWORD
  #         valueFrom:
  #           secretKeyRef:
  #             name: postgres-secret-config
  #             key: password
  #       - name: POSTGRES_HOST
  #         valueFrom:
  #           secretKeyRef:
  #             name: postgres-secret-config
  #             key: host
  #       - name: POSTGRES_PORT
  #         valueFrom:
  #           secretKeyRef:
  #             name: postgres-secret-config
  #             key: port
  #     command: [python]
  #     source: |
  #       import sys

  #       from wfunc import func

  #       func.post_notebook('bitcoin','maythamalherz.com')
  #       sys.exit()


