apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  # - context: blog/src/blog
  #   image: blog
  - context: KDSC/workflow/src/postgres
    image: postgres
  - context: KDSC/workflow/src/jupyter-viola
    image: jup
  - context: KDSC/workflow/src/germanen
    image: germanen-worker
  - context: KDSC/workflow/src/bitcoin
    image: bitcoin-worker
  - context: KDSC/workflow/src/getter
    image: getter-worker
  - context: KDSC/workflow/src/psql
    image: psql-worker
  # - context: KDSC/src/deliveryhero
  #   image: deliveryhero-worker



# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - KDSC/kubernetes-manifests/**
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
