apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bitcoin-comment-getter-
spec:
  entrypoint: main-block
  templates:

  # main block
  - name: main-block
    parallelism: 1
    steps:

    # generate list for reddit missing data
    - - name: generate-list-reddit
        template: generate-list-reddit

    # stream donwload reddit comments, filter non r/Bitcoin comments, load to gcs.
    - - name: get
        template: bitcoin-get-comments
        arguments:
          parameters:
          - name: url
            value: "{{item}}"
        withParam: "{{steps.generate-list-reddit.outputs.result}}"
  

  - name: generate-list-reddit
    script:
      image: gcr.io/kdcc-282418/python-worker
      command: [python]
      source: |
        import json
        import sys
        
        def generate_year_month():
          results = []
          for i in range(2018,2019): 
              for j in range(5,13):
                  if i == 2017 and j < 11:
                      pass
                  else:
                      results.append(str(i) + '-' + str(j).zfill(2))
          return ["https://files.pushshift.io/reddit/comments/RC_{}.xz".format(x) for x in results]
        
        json.dump(generate_year_month(), sys.stdout)

  - name: bitcoin-get-comments
    inputs:
      parameters:
      - name: url
    script:
      image: gcr.io/kdcc-282418/getter-worker
      command: [python]
      source: |
        from wfunc import func
        import os
      
        bucket = 'workflowkddc' 
        prefix = 'Bitcoin/comments' 
        filetype = 'txt'
        url = "{{inputs.parameters.url}}"
        # path = 'gs://workflowkddc/Bitcoin/RC_2011-01.txt'
        path = func.get_parse_json_to_gcs(url, bucket, prefix, filetype)


  # if not os.path.exists('tmp'):
  #   os.makedirs('tmp')
  # with open("/tmp/path.txt", 'w') as w:
  #   w.write(path)
  # # print('func.get_parse_json_to_gcs')

    # outputs:
    #   parameters:
    #   - name: path       # name of output parameter
    #     valueFrom:
    #       path: /tmp/path.txt

