apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bitcoin-price-getter-
spec:
  entrypoint: main-block
  templates:

  # main block
  - name: main-block
    parallelism: 2
    steps:
    - - name: bitcoin-get-price
        template: bitcoin-get-price
        arguments:
          parameters:
          - name: url
            value: "{{item}}"
        withItems:             
        - https://storage.googleapis.com/workflowkddc/publicex/bitcoin/price/bitstampUSD_1-min_data_2012-01-01_to_2020-04-22.csv
        - https://storage.googleapis.com/workflowkddc/publicex/bitcoin/price/coinbaseUSD_1-min_data_2014-12-01_to_2019-01-09.csv

  - name: bitcoin-get-price
    inputs:
      parameters:
      - name: url
    script:
      image: gcr.io/kdcc-282418/psql-worker
      command: [sh, -c]
      args: ['f="$(basename -- {{inputs.parameters.url}})";
        fgs="gs://workflowkddc/bitcoin/price/$f";
        curl {{inputs.parameters.url}} | gsutil cp - $fgs;
      ']
