---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jup
  template:
    metadata:
      labels:
        app: jup
    spec:
      containers:
      - name: jup
        image: jup
        env:
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret-config
                key: access_key
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret-config
                key: key_id
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgres-secret-config
                key: dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret-config
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret-config
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-secret-config
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-secret-config
                key: port
        command: ["/bin/sh","-c"]
        args: ["jupyter trust bitcoin.ipynb;voila bitcoin.ipynb --ExecutePreprocessor.timeout=180 --port 3001" ]
      # nodeSelector: # voila --debug test.ipynb --ExecutePreprocessor.timeout=180 --port 3001; ls -al
      #   memory: high 
---
apiVersion: v1
kind: Service
metadata:
  name: jup
spec:
  type: NodePort
  selector:
    app: jup
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
