apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
  
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 5432
  selector:
   app: postgres
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: argo
  # labels:
  #   app: postgres
spec:
  type: ExternalName
  externalName: postgres.default.cluster.local
  ports:
  - port: 27017

    # apiVersion: v1
    # kind: Service
    # metadata:
    #   name: mongo
    #   labels:
    #     name: mongo
    # spec:
    #   ports:
    #   - protocol: TCP
    #     port: 27017
    #     targetPort: 27017
    #   selector:
    #     role: mongo