apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-worker
spec:
  selector:
    matchLabels:
      app: psql-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: psql-worker
    spec:
      containers:
      - name: psql-worker
        image: psql-worker
        command: [ "tail", "-f", "/dev/null" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: dbname
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: password
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: port
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      


