apiVersion: v1
data:
  accesskey: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  secretkey: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: argo-artifacts
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-06-07T20:34:54Z"
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-5.0.26
    heritage: Helm
    release: argo-artifacts
  name: argo-artifacts
  namespace: argo
  resourceVersion: "13422113"
  selfLink: /api/v1/namespaces/default/secrets/argo-artifacts
  uid: b25a1bf7-c6ac-455a-8b54-69b79f715c6c
type: Opaque
