{{ if  .Values.Db.Enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  POSTGRES_PASSWORD: {{ if .Values.PostgresPassword }}{{ .Values.PostgresPassword | b64enc | quote }}{{ else }}{{ randAlphaNum 10 | b64enc | quote }}{{ end }}
{{ if .Values.POSTGRES_DB }}
  POSTGRES_DB: {{ .Values.PostgresDb | b64enc | quote }}
{{- end }}
{{ if .Values.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.PostgresUser | b64enc | quote }}
{{- end }}
{{- end }}
