apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scrap-
spec:
  entrypoint: scrap
  templates:
    - name: scrap
      script:
        
        image: gcr.io/kdcc-272111/python-worker:latest
        envFrom:
          - secretRef:
              name: argo-artifacts
        # command: [printenv]
        env:
          - name: POSTGRES_HOST
            value: postgres.default
          - name: POSTGRES_PORT
            value: "27017"
          # - name: CONFIG_FILE
          #   value: /etc/config/config.yaml
          - name: POSTGRES_DATABASE
            value: eco
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: 1234admin
        command: [python]
        source: |
            import mualchemy.aualchemy as au
            pdates, search, product, sales, seller , session = au.tables()
            sellertable = session.query(seller).filter_by(rated = None).first()# clean
            s = sellertable# cleab
            sellername = s.name
            seller_id = s.id
  # - name: heads
  #   container:
  #     image: alpine:3.6
  #     command: [sh, -c]
  #     args: ["echo \"it was heads\""]
#
  # - name: tails
  #   container:
  #     image: alpine:3.6
  #     command: [sh, -c]
  #     args: ["echo \"it was tails\""]
